### ISSUE TITLE
Mismatch column names

### ISSUE THREAD

**Issue by colbyaustinbrown** [mggg-states/PA-shapefiles#1]
In the shapefile, the 538 compact plan is called `538CPCT__1` (with two underscores), but in the readme, it is called `538CPCT_1` (with one underscore).

**Comment by maxhully** [comment]
The README has two underscores: 
![two_underscores](https://user-images.githubusercontent.com/8108892/61659602-d0851d00-ac95-11e9-9a1a-d2436a72312f.png)

**Comment by colbyaustinbrown** [comment]
The PA folder has its own README.md and it is that file specifically that has only one underscore. I did not realize that the README was different or I would have been more specific.
https://github.com/mggg-states/PA-shapefiles/tree/master/PA
