### ISSUE TITLE
PA_VTD.shp  vs PA_VTD_PLANS.shp

### ISSUE THREAD

**Issue by dinosg** [mggg-states/PA-shapefiles#2]
Hello,
in the basic gerrychain docs (https://gerrychain.readthedocs.io/en/latest/user/quickstart.html)
the very 1st command in the example template is

graph = Graph.from_file("./PA_VTD.shp")

with a reference to this github archive for the VTD's   but the files in the PA library include PA_VTD_PLANS.shp  not PA_VTD.shp.
they are not interchangeable (having tried copying PA_VTD_PLANS.shp --> PA_VTD.shp)

so the how-to guide crashes on the 1st step

**Comment by RKBuck1** [comment]
This is an issue with the GerryChain documentation, not the shapefile per se. I will speak with the folks maintaining that repo about updating the docs.
