### ISSUE TITLE
missing key, '2011_PLA_1' in shapefile

### ISSUE THREAD

**Issue by dinosg** [mggg-states/PA-shapefiles#3]
was able to perform
command 'graph = Graph.from_file("./PA_VTD.shp")'

by changing filename as below:
'graph = Graph.from_file("./PA_VTD_PLANS.shp") ', corresponding to the actual data files in the PA shapefiles https://github.com/mggg-states/PA-shapefiles/blob/master/README.md

- but - 
the next code block fails:
initial_partition = Partition(
    graph,
    assignment="2011_PLA_1",
    updaters={
        "cut_edges": cut_edges,
        "population": Tally("TOT_POP", alias="population"),
        "SEN12": election
    }
)

yielding error

Traceback (most recent call last):

  File "<ipython-input-13-a1f7d53c7ef8>", line 7, in <module>
    "SEN12": election

  File "/Users/dpg/opt/anaconda3/envs/spyder-4.0.1/lib/python3.7/site-packages/gerrychain/partition/partition.py", line 35, in __init__
    self._first_time(graph, assignment, updaters)

  File "/Users/dpg/opt/anaconda3/envs/spyder-4.0.1/lib/python3.7/site-packages/gerrychain/partition/partition.py", line 45, in _first_time
    self.assignment = get_assignment(assignment, graph)

  File "/Users/dpg/opt/anaconda3/envs/spyder-4.0.1/lib/python3.7/site-packages/gerrychain/partition/assignment.py", line 117, in get_assignment
    {node: graph.nodes[node][assignment] for node in graph}

  File "/Users/dpg/opt/anaconda3/envs/spyder-4.0.1/lib/python3.7/site-packages/gerrychain/partition/assignment.py", line 117, in <dictcomp>
    {node: graph.nodes[node][assignment] for node in graph}

KeyError: '2011_PLA_1'

**Comment by dinosg** [comment]
the graph object resulting from the initial assignment indeed does not appear to have the '2011_PLA_1' attribute. Printing out the graph._node would appear to list the node information with dict assignments as follows:

graph._node

'GEOID10': '420171420',
  'VTDI10': 'A',
  'NAME10': 'LOWER SOUTHAMPTON TWP VTD EAST ED 03',
  'NAMELSAD10': 'LOWER SOUTHAMPTON TWP VTD EAST ED 03',
  'LSAD10': '00',
  'MTFCC10': 'G5240',
  'FUNCSTAT10': 'N',
  'ALAND10': 1580883,
  'AWATER10': 60671,
  'INTPTLAT10': '+40.1583255',
  'INTPTLON10': '-074.9590930',
  'TOTPOP': 1984,
  'NH_WHITE': 1877,
  'NH_BLACK': 21,
  'NH_AMIN': 3,
  'NH_ASIAN': 18,
  'NH_NHPI': 0,
  'NH_OTHER': 3,
  'NH_2MORE': 17,
  'HISP': 45,
  'H_WHITE': 28,
  'H_BLACK': 0,
  'H_AMIN': 6,
  'H_ASIAN': 0,
  'H_NHPI': 0,
  'H_OTHER': 8,
  'H_2MORE': 3,
  'VAP': 1544,
  'HVAP': 32,
  'WVAP': 1470,
  'BVAP': 15,
  'AMINVAP': 3,
  'ASIANVAP': 13,
  'NHPIVAP': 0,
  'OTHERVAP': 0,
  '2MOREVAP': 11,
  'ATG12D': 512.0913011721888,
  'ATG12R': 505.0900529139752,
  'F2014GOVD': 332.0592031038411,
  'F2014GOVR': 354.06312620108366,
  'GOV10D': 327.0583114908315,
  'GOV10R': 480.085594848927,
  'PRES12D': 486.0866647845385,
  'PRES12O': 24.00427974244635,
  'PRES12R': 558.0995040118776,
  'SEN10D': 347.0618779428701,
  'SEN10R': 459.0818500742864,
  'T16ATGD': 516.0920144625965,
  'T16ATGR': 583.1039620769259,
  'T16PRESD': 478.0852382037231,
  'T16PRESOTH': 42.00748954928111,
  'T16PRESR': 620.1105600131973,
  'T16SEND': 483.08612981673275,
  'T16SENR': 615.1096684001877,
  'USS12D': 514.0916578173926,
  'USS12R': 512.0913011721888,
  'REMEDIAL': '01',
  'GOV': '8',
  'TS': 8,
  'CD_2011': 8,
  'SEND': 6,
  'HDIST': 142,
  '538DEM': '08',
  '538GOP': '08',
  '538CMPCT': '08',
  'geometry': <shapely.geometry.polygon.Polygon at 0x125606110>},
 925: {'boundary_node': False,
  'area': 0.00012578788100004427,
  'STATEFP10': '42',
  'COUNTYFP10': '017',
  'VTDST10': '1430',

etc. etc.

**Comment by drdeford** [comment]
Good catch! It looks like the column name for that plan has been replaced with CD_2011. I'm updating the gerrychain docs with this today.

**Comment by dinosg** [comment]
yup!!!  After a little detective work w/ object viewer I came to the same conclusion. It also turns out that dict label TOT_POP is really TOTPOP. so the command that works is:
initial_partition = Partition(
    graph,
    assignment="CD_2011",
    updaters={
        "cut_edges": cut_edges,
        "population": Tally("TOTPOP", alias="population"),
        "SEN12": election
    }
)

where TOTPOP is used not TOT_POP and CD_2011 like you say.

BUT... now running around on

chain = MarkovChain(
    proposal=propose_random_flip,
    constraints=[single_flip_contiguous],
    accept=always_accept,
    initial_state=initial_partition,
    total_steps=1000
)


Says: ValueError: The given initial_state is not valid according is_valid. The failed constraints were: single_flip_contiguous

**Comment by dinosg** [comment]
it would also be nice if initial_partition were viewable & inspectable with the object viewer (I'm working in spyder) as to get an idea what's in this object. So when things run aground there are clues. (object viewer on initial_partition fails, with error 'Spyder was unable to retrieve the value of this variable from the console. The error message was: KeyError('__getstate__')

but maybe you're using a different python interface where this complex object can be seen (if so, which one?)

**Comment by drdeford** [comment]
The dual graph needs two additional edges to be added in order for the 2011 (and GOV) plans to be contiguous, which is what is causing the single_flip_contiguous error. I uploaded a.json with this all fixed and updated the docs at mggg/gerrychain. You can see the new versions for now by clicking on the .rst and .md files directly here: https://github.com/mggg/GerryChain/tree/master/docs/user

**Comment by drdeford** [comment]
I'm not sure about the object viewer specifically, but the partition object contains a whole lot of stuff, since it is the fundamental object for the package. The API is pretty complete: https://gerrychain.readthedocs.io/en/latest/api.html#module-gerrychain.partition 
but I don't know a good way to summarize all the info of a single partition.

**Comment by drdeford** [comment]
The updates have propagated into the main docs now.
